<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-02-16T11:03:27Z" name="Suite" finished-at="2022-02-16T11:03:27Z" duration-ms="15">
    <groups>
    </groups>
    <test started-at="2022-02-16T11:03:27Z" name="Firefox Tests" finished-at="2022-02-16T11:03:27Z" duration-ms="2">
    </test> <!-- Firefox Tests -->
    <test started-at="2022-02-16T11:03:27Z" name="Chrome Tests" finished-at="2022-02-16T11:03:27Z" duration-ms="2">
    </test> <!-- Chrome Tests -->
    <test started-at="2022-02-16T11:03:27Z" name="API Tests" finished-at="2022-02-16T11:03:27Z" duration-ms="15">
      <class name="ui.selenium_tests.Test2API">
        <test-method signature="verifyHardGoodInRestResponse()[pri:0, instance:ui.selenium_tests.Test2API@503d687a]" started-at="2022-02-16T11:03:27Z" name="verifyHardGoodInRestResponse" finished-at="2022-02-16T11:03:27Z" duration-ms="3" status="FAIL">
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[io/restassured/RestAssured]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: io/restassured/RestAssured
at ui.selenium_tests.Test2API.verifyHardGoodInRestResponse(Test2API.java:13)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: io.restassured.RestAssured
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
... 21 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHardGoodInRestResponse -->
      </class> <!-- ui.selenium_tests.Test2API -->
    </test> <!-- API Tests -->
  </suite> <!-- Suite -->
</testng-results>
